### ISSUE TITLE
Policies are really Configurations

### ISSUE THREAD

**Issue by britram** [mami-project/draft-trammell-post-sockets#15]

**Comment by mirjak** [comment]
No idea...

**Comment by tfpauly** [comment]
Great question!

I think we've been using Parameters and Policy Context fairly interchangeably. Based on the definition in the draft, the Policy Content is essentially the parameters that influence the policy of what you end up using for your path, and what protocols you use. The broader term "Parameters" may include other bits that don't as naturally fit underneath Policy Context; the draft now mentions things like the certificates being parameters to create an association with, etc. Essentially any protocol-specific tuning parameters aren't as clearly part of the "policy", since the policy engine may not care about these parameters; but they are likely set at the same time as the other bits of Policy Context.

**Comment by britram** [comment]
So I *think* in the most general case that a policy context is merely a key-value mapping, where certain keys are things that Post cares about internally (security parameters for cryptosep, references to protocols that can show up in a stack instance, and so on), certain keys are protocol specific, certain keys might only be used by applications, and so on, with a set of rules or metarules for how context inheritance works.

So everything that's a Parameter now is basically a... policy context element?

From a cleanliness-of-the-draft thing, it'd be nice if the parameters you used to boot an association out-of-band came from the same source as the policy information -- although now, policy might not be the right word...

To discuss on the call, certainly.

**Comment by chris-wood** [comment]
s/Parameters/Configuration!

**Comment by tfpauly** [comment]
Opened PR #23
